MyProject/Models/ErrorViewModel.cs
namespace MyProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyProject/Controllers/Base/BaseController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace MyProject.Controllers.Base
{
    public class BaseController : Controller
    {
        protected readonly IMediator _mediator;
        public BaseController(IMediator mediator)
        {
            _mediator = mediator;
        }
    }
}

MyProject/Controllers/HomeController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using MyProject.Application.Services.Users.Queries;
using MyProject.Models;
using System.Diagnostics;

namespace MyProject.Controllers
{
    public class HomeController : Controller
    {

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyProject/Controllers/RolesController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using MyProject.Application.Services.Roles.Queries;
using MyProject.Controllers.Base;

namespace MyProject.Controllers
{
    public class RolesController : BaseController
    {
        public RolesController(IMediator mediator) : base(mediator)
        {
        }

        public async Task<IActionResult> Index(CancellationToken cancellationToken)
        {
            var roles = await _mediator.Send(new GetRolesQuery(cancellationToken));
            return View(roles);
        }
    }
}

MyProject/Controllers/UsersController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyProject.Application.Services.Roles.Queries;
using MyProject.Application.Services.Users.Commands;
using MyProject.Application.Services.Users.Queries;
using MyProject.Controllers.Base;
using MyProject.DataAccess.ViewModels.Roles.Queries.GetRoles;
using MyProject.DataAccess.ViewModels.Users.Commands.CreateUser;
using MyProject.DataAccess.ViewModels.Users.Commands.DeleteUser;
using MyProject.DataAccess.ViewModels.Users.Commands.UpdateUser;
using MyProject.DataAccess.ViewModels.Users.Queries.GetUser;

namespace MyProject.Controllers
{
    public class UsersController : BaseController
    {
        public UsersController(IMediator mediator) : base(mediator)
        {
        }

        [HttpGet]
        public async Task<IActionResult> Index(CancellationToken cancellationToken)
        {
            var users = await _mediator.Send(new GetUsersQuery(cancellationToken));
            return View(users);
        }


        [HttpGet]
        public async Task<IActionResult> Create(CancellationToken cancellationToken)
        {
            ViewBag.Roles = new SelectList(await _mediator.Send(new GetRolesQuery(cancellationToken)),"Id", "Title");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserRequest request, CancellationToken cancellationToken)
        {
            var createUser = await _mediator.Send(new CreateUserCommand(request, cancellationToken));

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(GetUserByIdRequest request, CancellationToken cancellationToken)
        {
            var user = await _mediator.Send(new GetUserByIdQuery(request, cancellationToken));
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateUserRequest request, CancellationToken cancellationToken)
        {
            var userUpdate = await _mediator.Send(new UpdateUserCommand(request, cancellationToken));

            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public async Task<IActionResult> GetUser(GetUserByIdRequest request, CancellationToken cancellationToken)
        {
            var user = await _mediator.Send(new GetUserByIdQuery(request, cancellationToken));
            return View(user);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(DeleteUserRequest request, CancellationToken cancellationToken)
        {
            await _mediator.Send(new DeleteUserCommand(request, cancellationToken));

            return RedirectToAction(nameof(Index));
        }

    }
}

MyProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "صفحه ی اصلی سایت";
}

<div class="container-fluid">
    
    <h1 class="text-center text-primary">به سایت تستی من خوش آمدید</h1>
</div>

MyProject/Views/Roles/Index.cshtml
@using MyProject.DataAccess.ViewModels.Roles.Queries.GetRoles

@model List<GetRolesResponse>
@{
    ViewData["Title"] = "Index";
}

<table class="table table-bordered table-hover">
    <tr>
        <th>آیدی</th>
        <th>عنوان</th>
    </tr>

    @foreach (var role in Model)
    {
        <tr>
            <td>@role.Id</td>
            <td>@role.Title</td>
        </tr>
    }

</table>

MyProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyProject.styles.css" asp-append-version="true" />
</head>
<body dir="rtl">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">صفحه ی اصلی</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Users" asp-action="Index">کاربران</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Roles" asp-action="Index">نقش های کاربری</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 1403 - MyProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyProject/Views/Users/Create.cshtml
@using MyProject.DataAccess.ViewModels.Users.Commands.CreateUser
@using MyProject.DataAccess.ViewModels.Users.Queries.GetUsers
@model CreateUserRequest
@{
    ViewData["Title"] = "افزودن کاربر";
}


<form asp-controller="Users" asp-action="Create">

    <label asp-for="FirstName"></label>
    <input type="text" asp-for="FirstName" class="form-control" />


    <label asp-for="LastName"></label>
    <input type="text" asp-for="LastName" class="form-control" />
    
    <select asp-items="@ViewBag.Roles" ></select>

    <input type="submit" class="btn btn-success m-2" value="افزودن کاربر" />

</form>

MyProject/Views/Users/GetUser.cshtml
@using MyProject.DataAccess.ViewModels.Users.Queries.GetUser
@model GetUserByIdResponse

@{
    ViewData["Title"] = "اطلاعات کاربر";
}

<table class="table table-bordered">
    <tr>
        <td>نام</td>
        <td>نام خانوادگی</td>
    </tr>

    <tr>
        <td>@Model.FirstName</td>
        <td>@Model.LastName</td>
    </tr>
</table>

MyProject/Views/Users/Index.cshtml
@using MyProject.DataAccess.ViewModels.Users.Queries.GetUsers
@model IEnumerable<GetUsersResponse>

@{
    ViewData["Title"] = "کاربران";
    
}

<div class="container-fluid">
    <a class="btn btn-primary m-2" asp-action="Create" asp-controller="Users">افزودن کاربر</a>
    <table class="table table-bordered table-hover">
        <tr>
            <td>آیدی</td>
            <td>نام</td>
            <td>نام خانوادگی</td>
            <td>عملیات</td>
        </tr>

        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Id</td>
                <td>@user.FirstName</td>
                <td>@user.LastName</td>
                <td>
                    <a class="btn btn-warning" asp-action="Update" asp-route-Id="@user.Id">ویرایش</a>
                    <a class="btn btn-info" asp-action="GetUser" asp-route-Id="@user.Id">جزئیات</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-Id="@user.Id">حذف</a>
                </td>

            </tr>

        }
    </table>
</div>

MyProject/Views/Users/Update.cshtml
@using MyProject.DataAccess.ViewModels.Users.Queries.GetUser
@model GetUserByIdResponse

@{
    ViewData["Title"] = "ویرایش کاربر";
}

<form asp-action="Update" asp-controller="Users" method="post">

    <label class="form-label" asp-for="FirstName"></label>
    <input class="form-control" asp-for="FirstName" placeholder="@Model.FirstName" />

    <label class="form-label" asp-for="LastName"></label>
    <input class="form-control" asp-for="LastName" placeholder="@Model.LastName" />

    <input type="submit" class="btn btn-success m-2" value="ثبت اطلاعات" />
     
</form>